from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from fastapi import APIRouter
from pydantic import BaseModel, Field

from backend.app.core.config import settings


DISCLAIMER = (
    "This report is generated by an AI system for research and educational "
    "purposes only. It is not personalized financial advice, investment "
    "advice, or a recommendation to buy or sell any security. Always conduct "
    "your own research and consider consulting a licensed financial "
    "professional before making investment decisions."
)


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    service: str = "openalpha-api"
    version: str = settings.app_version
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AppInfoResponse(BaseModel):
    name: str
    positioning: str
    disclaimer: str
    health_url: str


router = APIRouter(tags=["system"])


@router.get("/", response_model=AppInfoResponse)
async def root() -> AppInfoResponse:
    return AppInfoResponse(
        name="OpenAlpha",
        positioning="AI stock reports you can audit.",
        disclaimer=DISCLAIMER,
        health_url="/api/health",
    )


@router.get("/api/health", response_model=HealthResponse)
async def health() -> HealthResponse:
    return HealthResponse()
