from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from backend.app.llm.base import normalize_provider_name


AIView: TypeAlias = Literal[
    "bullish",
    "slightly_bullish",
    "neutral",
    "slightly_bearish",
    "bearish",
    "insufficient_data",
]
AgentName: TypeAlias = Literal[
    "data_collector",
    "technical_agent",
    "fundamental_agent",
    "news_sentiment_agent",
    "bull_case_agent",
    "bear_case_agent",
    "risk_review_agent",
    "thesis_agent",
    "critic_agent",
    "report_writer_agent",
]
AgentStatus: TypeAlias = Literal["pending", "running", "completed", "partial", "failed"]
DataStatus: TypeAlias = Literal["available", "partial", "missing"]
Depth: TypeAlias = Literal["quick", "standard", "deep"]
Horizon: TypeAlias = Literal["1w", "1m", "3m", "6m", "1y"]
Language: TypeAlias = Literal["en", "tr"]
Market: TypeAlias = Literal["US", "GLOBAL"]
RiskLevel: TypeAlias = Literal[
    "low",
    "medium",
    "moderate",
    "high",
    "critical",
    "very_high",
    "unknown",
    "insufficient_data",
]

DISCLAIMER = (
    "This report is generated by an AI system for research and educational "
    "purposes only. It is not personalized financial advice, investment "
    "advice, or a recommendation to buy or sell any security. Always conduct "
    "your own research and consider consulting a licensed financial "
    "professional before making investment decisions."
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def normalize_symbol_value(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    symbol = value.strip().upper()
    if not symbol:
        raise ValueError("symbol must not be empty")
    return symbol


class OpenAlphaSchema(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class AnalysisRequest(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    market: Market = "US"
    horizon: Horizon
    depth: Depth = "standard"
    language: Language = "en"
    llm_provider: str = Field(default="openai", min_length=1, max_length=64)
    llm_model: str = Field(min_length=1, max_length=120)
    custom_question: str | None = Field(default=None, max_length=1000)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)

    @field_validator("llm_provider", "llm_model", mode="before")
    @classmethod
    def strip_required_text(cls, value: Any) -> Any:
        if not isinstance(value, str):
            return value
        stripped = value.strip()
        if not stripped:
            raise ValueError("value must not be empty")
        return stripped

    @field_validator("llm_provider")
    @classmethod
    def canonicalize_provider(cls, value: str) -> str:
        return normalize_provider_name(value)


class DataSource(OpenAlphaSchema):
    name: str = Field(min_length=1, max_length=120)
    provider: str = Field(min_length=1, max_length=120)
    status: DataStatus = "available"
    url: str | None = None
    fetched_at: datetime = Field(default_factory=utc_now)
    notes: list[str] = Field(default_factory=list)


class PriceBar(OpenAlphaSchema):
    timestamp: datetime
    open: float | None = None
    high: float | None = None
    low: float | None = None
    close: float
    adjusted_close: float | None = None
    volume: int | None = Field(default=None, ge=0)


class Quote(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    price: float
    currency: str = Field(default="USD", min_length=3, max_length=8)
    as_of: datetime
    change: float | None = None
    change_percent: float | None = None
    market_cap: float | None = Field(default=None, ge=0)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class CompanyProfile(OpenAlphaSchema):
    name: str | None = None
    exchange: str | None = None
    sector: str | None = None
    industry: str | None = None
    country: str | None = None
    website: str | None = None
    description: str | None = None


class NewsItem(OpenAlphaSchema):
    title: str = Field(min_length=1)
    source: str = Field(min_length=1)
    published_at: datetime | None = None
    url: str | None = None
    summary: str | None = None
    sentiment_score: float | None = Field(default=None, ge=-1, le=1)


class FinancialSnapshot(OpenAlphaSchema):
    period_end: date | None = None
    revenue: float | None = None
    gross_margin: float | None = None
    operating_margin: float | None = None
    net_income: float | None = None
    eps: float | None = None
    free_cash_flow: float | None = None
    debt_to_equity: float | None = None
    pe_ratio: float | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class MarketDataBundle(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    market: Market = "US"
    quote: Quote | None = None
    price_history: list[PriceBar] = Field(default_factory=list)
    company_profile: CompanyProfile | None = None
    financials: FinancialSnapshot | None = None
    news: list[NewsItem] = Field(default_factory=list)
    sources: list[DataSource] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    data_quality_score: float | None = Field(default=None, ge=0, le=1)
    as_of: datetime = Field(default_factory=utc_now)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class IndicatorSignal(OpenAlphaSchema):
    name: str = Field(min_length=1)
    value: float | None = None
    signal: Literal["bullish", "neutral", "bearish", "insufficient_data"]
    explanation: str | None = None


class MacdValue(OpenAlphaSchema):
    macd: float | None = None
    signal: float | None = None
    histogram: float | None = None


class BollingerBands(OpenAlphaSchema):
    upper: float | None = None
    middle: float | None = None
    lower: float | None = None


class VolumeTrendValue(OpenAlphaSchema):
    direction: Literal["increasing", "decreasing", "flat", "insufficient_data"]
    short_average: float | None = Field(default=None, ge=0)
    long_average: float | None = Field(default=None, ge=0)
    ratio: float | None = Field(default=None, ge=0)


class IndicatorBundle(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    horizon: Horizon
    generated_at: datetime = Field(default_factory=utc_now)
    rsi: IndicatorSignal | None = None
    macd: MacdValue | None = None
    moving_averages: dict[str, float] = Field(default_factory=dict)
    bollinger_bands: BollingerBands | None = None
    atr: float | None = Field(default=None, ge=0)
    volume_trend: VolumeTrendValue | None = None
    volatility: float | None = Field(default=None, ge=0)
    support_levels: list[float] = Field(default_factory=list)
    resistance_levels: list[float] = Field(default_factory=list)
    signals: list[IndicatorSignal] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class CostTrace(OpenAlphaSchema):
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    agent_name: AgentName
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: float = Field(default=0, ge=0)
    cost_type: str = Field(default="api", min_length=1, max_length=64)
    duration_ms: int = Field(default=0, ge=0)
    warnings: list[str] = Field(default_factory=list)
    parsing_errors: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)


class EvidenceItem(OpenAlphaSchema):
    claim: str = Field(min_length=1)
    source: str | None = None
    confidence: float | None = Field(default=None, ge=0, le=1)
    url: str | None = None


class DataQualitySummary(OpenAlphaSchema):
    price_data_status: DataStatus = "missing"
    news_data_status: DataStatus = "missing"
    fundamentals_status: DataStatus = "missing"
    provider_names: list[str] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    score: float | None = Field(default=None, ge=0, le=1)


class DataCollectorOutput(OpenAlphaSchema):
    market_data: MarketDataBundle
    data_quality: DataQualitySummary


class TechnicalLevel(OpenAlphaSchema):
    price: float
    reason: str = Field(min_length=1)
    strength: Literal["weak", "moderate", "strong"]


class TechnicalAgentOutput(OpenAlphaSchema):
    view: AIView
    confidence: float = Field(ge=0, le=1)
    summary: str
    key_signals: list[str] = Field(default_factory=list)
    support_levels: list[TechnicalLevel] = Field(default_factory=list)
    resistance_levels: list[TechnicalLevel] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class FundamentalAgentOutput(OpenAlphaSchema):
    fundamental_view: AIView
    confidence: float = Field(ge=0, le=1)
    summary: str
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    valuation_notes: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class NewsSentimentItem(OpenAlphaSchema):
    title: str = Field(min_length=1)
    source: str = Field(min_length=1)
    published_at: datetime | None = None
    summary: str = Field(min_length=1)
    sentiment: Literal["positive", "neutral", "negative", "mixed", "unclear"]
    relevance: Literal["low", "medium", "high"]
    url: str | None = None


class NewsSentimentOutput(OpenAlphaSchema):
    view: AIView
    confidence: float = Field(ge=0, le=1)
    sentiment_summary: str
    important_news: list[NewsSentimentItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


NewsSentimentAgentOutput = NewsSentimentOutput


class BullCaseAgentOutput(OpenAlphaSchema):
    bull_case: str
    main_arguments: list[str] = Field(default_factory=list)
    upside_conditions: list[str] = Field(default_factory=list)


class BearCaseAgentOutput(OpenAlphaSchema):
    bear_case: str
    main_risks: list[str] = Field(default_factory=list)
    downside_conditions: list[str] = Field(default_factory=list)


class RiskReviewAgentOutput(OpenAlphaSchema):
    risk_level: RiskLevel
    risk_score: float = Field(ge=0, le=100)
    main_risks: list[str] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    confidence_adjustment: float = Field(ge=-0.40, le=0)


class ThesisAgentOutput(OpenAlphaSchema):
    overall_view: AIView
    confidence: float = Field(ge=0, le=1)
    horizon: Horizon
    thesis: str
    base_case: str
    bull_case_summary: str
    bear_case_summary: str
    what_to_watch: list[str] = Field(default_factory=list)


class CriticAgentOutput(OpenAlphaSchema):
    passed: bool
    confidence: float = Field(ge=0, le=1)
    safety_notes: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    required_revisions: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ReportSection(OpenAlphaSchema):
    title: str = Field(min_length=1)
    body: str = Field(min_length=1)
    sources: list[str] = Field(default_factory=list)


class AgentSummaries(OpenAlphaSchema):
    technical: str = Field(min_length=1)
    news_sentiment: str = Field(min_length=1)
    bull_case: str = Field(min_length=1)
    bear_case: str = Field(min_length=1)
    risk_review: str = Field(min_length=1)


class FinalReportRiskSection(OpenAlphaSchema):
    risk_level: RiskLevel
    risk_score: float = Field(ge=0, le=100)
    main_risks: list[str] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    confidence_adjustment: float = Field(ge=-0.40, le=0)


class FinalReportDataQualitySection(OpenAlphaSchema):
    data_quality_score: float | None = Field(default=None, ge=0, le=1)
    price_data_status: DataStatus = "missing"
    news_data_status: DataStatus = "missing"
    company_profile_status: DataStatus = "missing"
    missing_data: list[str] = Field(default_factory=list)
    providers: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class FinalReportSourceItem(OpenAlphaSchema):
    name: str = Field(min_length=1, max_length=120)
    type: Literal["price", "news", "profile", "financials", "other"] = "other"
    provider: str = Field(min_length=1, max_length=120)
    url: str | None = None
    used_for: str = Field(min_length=1)


class FinalReportCostItem(OpenAlphaSchema):
    agent_name: AgentName
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: float = Field(default=0, ge=0)
    cost_type: str = Field(default="api", min_length=1, max_length=64)
    duration_ms: int = Field(default=0, ge=0)
    warnings: list[str] = Field(default_factory=list)
    parsing_errors: list[str] = Field(default_factory=list)


class FinalReportCostBreakdown(OpenAlphaSchema):
    total_estimated_cost_usd: float = Field(default=0, ge=0)
    items: list[FinalReportCostItem] = Field(default_factory=list)


class FinalReport(OpenAlphaSchema):
    title: str = Field(min_length=1)
    symbol: str = Field(min_length=1, max_length=32)
    company_name: str = Field(min_length=1)
    market: Market
    created_at: datetime = Field(default_factory=utc_now)
    latest_close: float | None = Field(default=None, ge=0)
    overall_view: AIView
    confidence: float = Field(ge=0, le=1)
    horizon: Horizon
    executive_summary: str = Field(min_length=1)
    investment_thesis: str = Field(min_length=1)
    base_case: str = Field(min_length=1)
    bull_case_summary: str = Field(min_length=1)
    bear_case_summary: str = Field(min_length=1)
    what_to_watch: list[str] = Field(default_factory=list)
    agent_summaries: AgentSummaries
    risk_section: FinalReportRiskSection
    data_quality_section: FinalReportDataQualitySection
    source_section: list[FinalReportSourceItem] = Field(default_factory=list)
    cost_breakdown: FinalReportCostBreakdown
    warnings: list[str] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER
    report_markdown: str = Field(min_length=1)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


ReportWriterOutput = FinalReport


AgentOutputContent: TypeAlias = (
    DataCollectorOutput
    | TechnicalAgentOutput
    | FundamentalAgentOutput
    | NewsSentimentOutput
    | BullCaseAgentOutput
    | BearCaseAgentOutput
    | RiskReviewAgentOutput
    | ThesisAgentOutput
    | CriticAgentOutput
    | FinalReport
    | dict[str, Any]
)


class AgentResult(OpenAlphaSchema):
    agent_name: AgentName
    status: AgentStatus
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: float = Field(default=0, ge=0)
    cost_type: str = Field(default="api", min_length=1, max_length=64)
    duration_ms: int = Field(default=0, ge=0)
    started_at: datetime = Field(default_factory=utc_now)
    finished_at: datetime | None = None
    output: AgentOutputContent | None = None
    data_used: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    parsing_errors: list[str] = Field(default_factory=list)
    error_message: str | None = None
    fatal_error: bool = False

    @model_validator(mode="after")
    def validate_finished_at(self) -> "AgentResult":
        if self.finished_at and self.finished_at < self.started_at:
            raise ValueError("finished_at must be after started_at")
        return self


class AnalysisContext(OpenAlphaSchema):
    run_id: str = Field(min_length=1, max_length=64)
    request: AnalysisRequest
    market_data: MarketDataBundle | None = None
    indicators: IndicatorBundle | None = None
    technical_output: TechnicalAgentOutput | None = None
    news_sentiment_output: NewsSentimentOutput | None = None
    bull_case_output: BullCaseAgentOutput | None = None
    bear_case_output: BearCaseAgentOutput | None = None
    risk_review_output: RiskReviewAgentOutput | None = None
    thesis_output: ThesisAgentOutput | None = None
    final_report: FinalReport | None = None
    data_quality: DataQualitySummary | None = None
    agent_results: list[AgentResult] = Field(default_factory=list)
    cost_traces: list[CostTrace] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    @property
    def total_cost_usd(self) -> float:
        return sum(trace.estimated_cost_usd for trace in self.cost_traces)
