from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


AIView: TypeAlias = Literal[
    "strong_bullish",
    "moderately_bullish",
    "neutral",
    "moderately_bearish",
    "strong_bearish",
    "insufficient_data",
]
AgentName: TypeAlias = Literal[
    "data_collector",
    "technical_agent",
    "fundamental_agent",
    "news_sentiment_agent",
    "bull_case_agent",
    "bear_case_agent",
    "risk_review_agent",
    "thesis_agent",
    "critic_agent",
    "report_writer_agent",
]
AgentStatus: TypeAlias = Literal["pending", "running", "completed", "partial", "failed"]
DataStatus: TypeAlias = Literal["available", "partial", "missing"]
Depth: TypeAlias = Literal["quick", "standard", "deep"]
Horizon: TypeAlias = Literal["1w", "1m", "3m", "6m", "1y"]
Language: TypeAlias = Literal["en", "tr"]
Market: TypeAlias = Literal["US", "GLOBAL"]
RiskLevel: TypeAlias = Literal["low", "medium", "high", "critical", "unknown"]

DISCLAIMER = (
    "This report is generated by an AI system for research and educational "
    "purposes only. It is not personalized financial advice, investment "
    "advice, or a recommendation to buy or sell any security. Always conduct "
    "your own research and consider consulting a licensed financial "
    "professional before making investment decisions."
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def normalize_symbol_value(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    symbol = value.strip().upper()
    if not symbol:
        raise ValueError("symbol must not be empty")
    return symbol


class OpenAlphaSchema(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class AnalysisRequest(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    market: Market = "US"
    horizon: Horizon
    depth: Depth = "standard"
    language: Language = "en"
    llm_provider: str = Field(default="openai", min_length=1, max_length=64)
    llm_model: str = Field(min_length=1, max_length=120)
    custom_question: str | None = Field(default=None, max_length=1000)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)

    @field_validator("llm_provider", "llm_model", mode="before")
    @classmethod
    def strip_required_text(cls, value: Any) -> Any:
        if not isinstance(value, str):
            return value
        stripped = value.strip()
        if not stripped:
            raise ValueError("value must not be empty")
        return stripped


class DataSource(OpenAlphaSchema):
    name: str = Field(min_length=1, max_length=120)
    provider: str = Field(min_length=1, max_length=120)
    status: DataStatus = "available"
    url: str | None = None
    fetched_at: datetime = Field(default_factory=utc_now)
    notes: list[str] = Field(default_factory=list)


class PriceBar(OpenAlphaSchema):
    timestamp: datetime
    open: float | None = None
    high: float | None = None
    low: float | None = None
    close: float
    adjusted_close: float | None = None
    volume: int | None = Field(default=None, ge=0)


class Quote(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    price: float
    currency: str = Field(default="USD", min_length=3, max_length=8)
    as_of: datetime
    change: float | None = None
    change_percent: float | None = None
    market_cap: float | None = Field(default=None, ge=0)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class CompanyProfile(OpenAlphaSchema):
    name: str | None = None
    exchange: str | None = None
    sector: str | None = None
    industry: str | None = None
    country: str | None = None
    website: str | None = None
    description: str | None = None


class NewsItem(OpenAlphaSchema):
    title: str = Field(min_length=1)
    source: str = Field(min_length=1)
    published_at: datetime | None = None
    url: str | None = None
    summary: str | None = None
    sentiment_score: float | None = Field(default=None, ge=-1, le=1)


class FinancialSnapshot(OpenAlphaSchema):
    period_end: date | None = None
    revenue: float | None = None
    gross_margin: float | None = None
    operating_margin: float | None = None
    net_income: float | None = None
    eps: float | None = None
    free_cash_flow: float | None = None
    debt_to_equity: float | None = None
    pe_ratio: float | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class MarketDataBundle(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    market: Market = "US"
    quote: Quote | None = None
    price_history: list[PriceBar] = Field(default_factory=list)
    company_profile: CompanyProfile | None = None
    financials: FinancialSnapshot | None = None
    news: list[NewsItem] = Field(default_factory=list)
    sources: list[DataSource] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    data_quality_score: float | None = Field(default=None, ge=0, le=1)
    as_of: datetime = Field(default_factory=utc_now)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class IndicatorSignal(OpenAlphaSchema):
    name: str = Field(min_length=1)
    value: float | None = None
    signal: Literal["bullish", "neutral", "bearish", "insufficient_data"]
    explanation: str | None = None


class MacdValue(OpenAlphaSchema):
    macd: float | None = None
    signal: float | None = None
    histogram: float | None = None


class BollingerBands(OpenAlphaSchema):
    upper: float | None = None
    middle: float | None = None
    lower: float | None = None


class IndicatorBundle(OpenAlphaSchema):
    symbol: str = Field(min_length=1, max_length=32)
    horizon: Horizon
    generated_at: datetime = Field(default_factory=utc_now)
    rsi: IndicatorSignal | None = None
    macd: MacdValue | None = None
    moving_averages: dict[str, float] = Field(default_factory=dict)
    bollinger_bands: BollingerBands | None = None
    atr: float | None = Field(default=None, ge=0)
    volatility: float | None = Field(default=None, ge=0)
    support_levels: list[float] = Field(default_factory=list)
    resistance_levels: list[float] = Field(default_factory=list)
    signals: list[IndicatorSignal] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)


class CostTrace(OpenAlphaSchema):
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    agent_name: AgentName
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: float = Field(default=0, ge=0)
    created_at: datetime = Field(default_factory=utc_now)


class EvidenceItem(OpenAlphaSchema):
    claim: str = Field(min_length=1)
    source: str | None = None
    confidence: float | None = Field(default=None, ge=0, le=1)
    url: str | None = None


class DataQualitySummary(OpenAlphaSchema):
    price_data_status: DataStatus = "missing"
    news_data_status: DataStatus = "missing"
    fundamentals_status: DataStatus = "missing"
    provider_names: list[str] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    score: float | None = Field(default=None, ge=0, le=1)


class DataCollectorOutput(OpenAlphaSchema):
    market_data: MarketDataBundle
    data_quality: DataQualitySummary


class TechnicalAgentOutput(OpenAlphaSchema):
    technical_view: AIView
    confidence: float = Field(ge=0, le=1)
    summary: str
    indicators: IndicatorBundle
    key_signals: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class FundamentalAgentOutput(OpenAlphaSchema):
    fundamental_view: AIView
    confidence: float = Field(ge=0, le=1)
    summary: str
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    valuation_notes: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class NewsSentimentAgentOutput(OpenAlphaSchema):
    sentiment_view: AIView
    sentiment_score: float | None = Field(default=None, ge=-1, le=1)
    confidence: float = Field(ge=0, le=1)
    summary: str
    key_headlines: list[NewsItem] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class BullCaseAgentOutput(OpenAlphaSchema):
    view: AIView
    confidence: float = Field(ge=0, le=1)
    thesis: str
    key_points: list[str] = Field(default_factory=list)
    catalysts: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class BearCaseAgentOutput(OpenAlphaSchema):
    view: AIView
    confidence: float = Field(ge=0, le=1)
    thesis: str
    key_points: list[str] = Field(default_factory=list)
    downside_risks: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class RiskReviewAgentOutput(OpenAlphaSchema):
    risk_level: RiskLevel
    risk_score: float | None = Field(default=None, ge=0, le=1)
    confidence: float = Field(ge=0, le=1)
    summary: str
    key_risks: list[str] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)
    mitigation_factors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ThesisAgentOutput(OpenAlphaSchema):
    ai_view: AIView
    confidence: float = Field(ge=0, le=1)
    risk_level: RiskLevel
    investment_thesis: str
    bull_case_summary: str
    bear_case_summary: str
    what_to_watch: list[str] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class CriticAgentOutput(OpenAlphaSchema):
    passed: bool
    confidence: float = Field(ge=0, le=1)
    safety_notes: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    required_revisions: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ReportSection(OpenAlphaSchema):
    title: str = Field(min_length=1)
    body: str = Field(min_length=1)
    sources: list[str] = Field(default_factory=list)


class ReportWriterOutput(OpenAlphaSchema):
    title: str = Field(min_length=1)
    executive_summary: str = Field(min_length=1)
    sections: list[ReportSection] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER


AgentOutputContent: TypeAlias = (
    DataCollectorOutput
    | TechnicalAgentOutput
    | FundamentalAgentOutput
    | NewsSentimentAgentOutput
    | BullCaseAgentOutput
    | BearCaseAgentOutput
    | RiskReviewAgentOutput
    | ThesisAgentOutput
    | CriticAgentOutput
    | ReportWriterOutput
    | dict[str, Any]
)


class AgentResult(OpenAlphaSchema):
    agent_name: AgentName
    status: AgentStatus
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: float = Field(default=0, ge=0)
    started_at: datetime = Field(default_factory=utc_now)
    finished_at: datetime | None = None
    output: AgentOutputContent | None = None
    data_used: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    parsing_errors: list[str] = Field(default_factory=list)
    error_message: str | None = None

    @model_validator(mode="after")
    def validate_finished_at(self) -> "AgentResult":
        if self.finished_at and self.finished_at < self.started_at:
            raise ValueError("finished_at must be after started_at")
        return self


class AnalysisContext(OpenAlphaSchema):
    run_id: str = Field(min_length=1, max_length=64)
    request: AnalysisRequest
    market_data: MarketDataBundle | None = None
    indicators: IndicatorBundle | None = None
    data_quality: DataQualitySummary | None = None
    agent_results: list[AgentResult] = Field(default_factory=list)
    cost_traces: list[CostTrace] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    @property
    def total_cost_usd(self) -> float:
        return sum(trace.estimated_cost_usd for trace in self.cost_traces)


class FinalReport(OpenAlphaSchema):
    report_id: str = Field(min_length=1, max_length=64)
    run_id: str = Field(min_length=1, max_length=64)
    request: AnalysisRequest
    symbol: str = Field(min_length=1, max_length=32)
    market: Market
    horizon: Horizon
    depth: Depth
    language: Language
    ai_view: AIView
    confidence: float = Field(ge=0, le=1)
    risk_level: RiskLevel
    price_at_report_time: float | None = None
    benchmark_price_at_report_time: float | None = None
    investment_thesis: str
    bull_case: list[str] = Field(default_factory=list)
    bear_case: list[str] = Field(default_factory=list)
    what_to_watch: list[str] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    sections: list[ReportSection] = Field(default_factory=list)
    market_data: MarketDataBundle | None = None
    indicators: IndicatorBundle | None = None
    data_quality: DataQualitySummary
    agent_results: list[AgentResult] = Field(default_factory=list)
    cost_traces: list[CostTrace] = Field(default_factory=list)
    total_cost_usd: float = Field(default=0, ge=0)
    provider: str = Field(min_length=1, max_length=64)
    model: str = Field(min_length=1, max_length=120)
    warnings: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=utc_now)
    disclaimer: str = DISCLAIMER

    @field_validator("symbol", mode="before")
    @classmethod
    def normalize_symbol(cls, value: Any) -> Any:
        return normalize_symbol_value(value)
