from __future__ import annotations

from datetime import UTC, datetime
from typing import Literal

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


DISCLAIMER = (
    "This report is generated by an AI system for research and educational "
    "purposes only. It is not personalized financial advice, investment "
    "advice, or a recommendation to buy or sell any security. Always conduct "
    "your own research and consider consulting a licensed financial "
    "professional before making investment decisions."
)


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    service: str = "openalpha-api"
    version: str = "0.1.0"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class AppInfoResponse(BaseModel):
    name: str
    positioning: str
    disclaimer: str
    health_url: str


def create_app() -> FastAPI:
    app = FastAPI(
        title="OpenAlpha API",
        description="Local-first AI equity research API.",
        version="0.1.0",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            "http://localhost:3000",
            "http://localhost:5173",
            "http://127.0.0.1:3000",
            "http://127.0.0.1:5173",
        ],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/", response_model=AppInfoResponse, tags=["system"])
    async def root() -> AppInfoResponse:
        return AppInfoResponse(
            name="OpenAlpha",
            positioning="AI stock reports you can audit.",
            disclaimer=DISCLAIMER,
            health_url="/api/health",
        )

    @app.get("/api/health", response_model=HealthResponse, tags=["system"])
    async def health() -> HealthResponse:
        return HealthResponse()

    return app


app = create_app()
