from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Literal

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from backend.app.core.config import settings
from backend.app.core.logging import configure_logging
from backend.app.db.session import init_db


logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This report is generated by an AI system for research and educational "
    "purposes only. It is not personalized financial advice, investment "
    "advice, or a recommendation to buy or sell any security. Always conduct "
    "your own research and consider consulting a licensed financial "
    "professional before making investment decisions."
)


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    service: str = "openalpha-api"
    version: str = settings.app_version
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AppInfoResponse(BaseModel):
    name: str
    positioning: str
    disclaimer: str
    health_url: str


@asynccontextmanager
async def lifespan(_app: FastAPI) -> AsyncIterator[None]:
    init_db()
    logger.info("Started %s in %s mode", settings.app_name, settings.environment)
    yield


def create_app() -> FastAPI:
    configure_logging(settings.log_level)

    app = FastAPI(
        title=settings.app_name,
        description="Local-first AI equity research API.",
        version=settings.app_version,
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/", response_model=AppInfoResponse, tags=["system"])
    async def root() -> AppInfoResponse:
        return AppInfoResponse(
            name="OpenAlpha",
            positioning="AI stock reports you can audit.",
            disclaimer=DISCLAIMER,
            health_url="/api/health",
        )

    @app.get("/api/health", response_model=HealthResponse, tags=["system"])
    async def health() -> HealthResponse:
        return HealthResponse()

    return app


app = create_app()
