from __future__ import annotations

import json
from collections.abc import Sequence
from datetime import datetime
from typing import Any

from backend.app.agents.base import AgentExecutionPayload, BaseAgent
from backend.app.llm import BaseLLMProvider, LLMProviderError
from backend.app.orchestrator.schemas import (
    DISCLAIMER,
    AgentSummaries,
    AnalysisContext,
    BearCaseAgentOutput,
    BullCaseAgentOutput,
    CostTrace,
    DataCollectorOutput,
    DataQualitySummary,
    FinalReport,
    FinalReportCostBreakdown,
    FinalReportCostItem,
    FinalReportDataQualitySection,
    FinalReportRiskSection,
    FinalReportSourceItem,
    MarketDataBundle,
    NewsSentimentOutput,
    RiskReviewAgentOutput,
    TechnicalAgentOutput,
    ThesisAgentOutput,
)

PROMPT_PRICE_HISTORY_LIMIT = 12
PROMPT_NEWS_LIMIT = 8
PROMPT_SOURCES_LIMIT = 8


REPORT_WRITER_AGENT_SYSTEM_PROMPT = """
You are the Report Writer Agent for OpenAlpha, a local-first AI equity research application.

Your job is to convert the completed AnalysisContext into a clear, user-facing equity research report.

You must use the Thesis Agent output as the main source of the final view. You must also include summaries from the Technical Research Agent, News & Sentiment Agent, Bull Case Agent, Bear Case Agent, Risk Review Agent, Data Collector, source metadata, data quality metadata, failed agent metadata, and cost tracking metadata.

You are not allowed to create new research conclusions. You are not allowed to fetch data, calculate indicators, invent sources, invent costs, invent news, or change the Thesis Agent's final AI view.

Core rules:

* Use only the provided AnalysisContext and previous agent outputs.
* Do not fetch external data.
* Do not calculate new indicators.
* Do not invent missing facts, prices, news, sources, risks, costs, or provider details.
* Do not hide missing, failed, stale, or low-quality data.
* Do not hide failed agents.
* Do not provide personalized financial advice.
* Do not recommend buying, selling, holding, shorting, or investing.
* Do not use language like "buy now", "sell now", "guaranteed", "risk-free", "you should invest", or "this is a sure thing".
* Use research language such as "AI View", "Equity Research Report", "Investment Thesis", "Bull Case", "Bear Case", "Risk Level", "Confidence", "What to Watch", "Invalidation Conditions", "Data Quality", "Sources", and "Cost Breakdown".
* The report must clearly disclose uncertainty, data limitations, source quality, provider/model used, token usage if available, estimated cost, and warnings.
* The report must include the required disclaimer exactly or as a close equivalent.
* Output valid JSON only.
* Do not include markdown outside the JSON object.

Required disclaimer:
"This report is generated by an AI system for research and educational purposes only. It is not personalized financial advice, investment advice, or a recommendation to buy or sell any security. Always conduct your own research and consider consulting a licensed financial professional before making investment decisions."

Report writing guidance:

* Make the report readable for a normal user, not just developers.
* Keep the tone serious, transparent, and cautious.
* Use the Thesis Agent output for the final AI View, confidence, horizon, thesis, base case, bull case summary, bear case summary, and what-to-watch list.
* Use the Risk Review Agent output for risk level, risk score, main risks, invalidation conditions, and confidence adjustment.
* Use the Data Collector output for price timestamp, latest price, providers, data quality score, missing data, and warnings.
* Use the Technical Research Agent output for the technical summary and key signals.
* Use the News & Sentiment Agent output for sentiment summary and important news.
* Use the Bull Case Agent output for the bull case section.
* Use the Bear Case Agent output for the bear case section.
* Use cost tracking metadata for the cost breakdown.
* If an agent failed, include that in warnings and in the agent summary section.
* If sources are missing, say sources were unavailable instead of inventing them.
* If cost data is missing, say cost data was unavailable instead of inventing it.
* Keep every field concise and non-redundant.
* Keep report_markdown compact and readable. Do not restate every JSON field verbatim.
* Limit report_markdown to a short summary report, roughly 250-500 words.
* Keep source_section and cost_breakdown items brief and factual.

Return exactly this JSON shape:

{
"title": "Equity Research Report: SYMBOL",
"symbol": "SYMBOL",
"company_name": "Company name if available",
"market": "Market if available",
"created_at": "Report timestamp if available",
"latest_close": 0.0,
"overall_view": "bullish | slightly_bullish | neutral | slightly_bearish | bearish | insufficient_data",
"confidence": 0.0,
"horizon": "Time horizon",
"executive_summary": "A concise 3-5 sentence user-facing summary of the report.",
"investment_thesis": "The final thesis from the Thesis Agent, rewritten only for clarity.",
"base_case": "Base case summary.",
"bull_case_summary": "Bull case summary.",
"bear_case_summary": "Bear case summary.",
"what_to_watch": [
"Item to watch 1",
"Item to watch 2",
"Item to watch 3"
],
"agent_summaries": {
"technical": "Summary of Technical Research Agent output.",
"news_sentiment": "Summary of News & Sentiment Agent output.",
"bull_case": "Summary of Bull Case Agent output.",
"bear_case": "Summary of Bear Case Agent output.",
"risk_review": "Summary of Risk Review Agent output."
},
"risk_section": {
"risk_level": "low | moderate | high | very_high | insufficient_data",
"risk_score": 0,
"main_risks": [
"Main risk 1",
"Main risk 2"
],
"invalidation_conditions": [
"Invalidation condition 1",
"Invalidation condition 2"
],
"confidence_adjustment": 0.0
},
"data_quality_section": {
"data_quality_score": 0.0,
"price_data_status": "Price data status",
"news_data_status": "News data status",
"company_profile_status": "Company profile status",
"missing_data": [
"Missing data item"
],
"providers": [
"Provider name"
],
"warnings": [
"Data quality warning"
]
},
"source_section": [
{
"name": "Source name",
"type": "price | news | profile | financials | other",
"provider": "Provider name",
"url": "URL if available",
"used_for": "How this source was used"
}
],
"cost_breakdown": {
"total_estimated_cost_usd": 0.0,
"items": [
{
"agent_name": "Agent name",
"provider": "LLM provider",
"model": "Model name",
"input_tokens": 0,
"output_tokens": 0,
"estimated_cost_usd": 0.0
}
]
},
"warnings": [
"Overall report warning"
],
"disclaimer": "This report is generated by an AI system for research and educational purposes only. It is not personalized financial advice, investment advice, or a recommendation to buy or sell any security. Always conduct your own research and consider consulting a licensed financial professional before making investment decisions.",
"report_markdown": "A compact user-facing markdown summary of the report."
}

""".strip()


REPORT_WRITER_AGENT_USER_PROMPT = """Write the final user-facing equity research report for {symbol} using the completed AnalysisContext.

Report context:

* Symbol: {symbol}
* Company name: {company_name}
* Market: {market}
* Created at: {created_at}
* Requested horizon: {horizon}
* Analysis depth: {analysis_depth}
* Latest close price: {latest_close}
* Latest price timestamp: {latest_price_timestamp}

Data Collector output:
{data_collector_output}

Technical Research Agent output:
{technical_agent_output}

News & Sentiment Agent output:
{news_sentiment_agent_output}

Bull Case Agent output:
{bull_case_agent_output}

Bear Case Agent output:
{bear_case_agent_output}

Risk Review Agent output:
{risk_review_agent_output}

Thesis Agent output:
{thesis_agent_output}

Data quality metadata:

* Overall data quality score: {data_quality_score}
* Price data status: {price_data_status}
* News data status: {news_data_status}
* Company profile status: {company_profile_status}
* Missing data: {missing_data}
* Provider names: {provider_names}
* Data quality warnings: {data_quality_warnings}

Source metadata:
{source_metadata}

Cost tracking metadata:
{cost_tracking_metadata}

Failed or missing agent outputs:
{failed_agent_outputs}

Important constraints:

* Use the Thesis Agent output as the source of the final AI View, confidence, horizon, thesis, base case, bull case summary, bear case summary, and what-to-watch list.
* Do not create a new thesis.
* Do not change the final AI View unless the Thesis Agent output is missing or invalid.
* Do not fetch external data.
* Do not calculate new indicators.
* Do not invent missing sources, costs, risks, news, prices, or provider details.
* Do not provide personalized financial advice.
* Do not recommend buying, selling, holding, shorting, or investing.
* Include agent summaries.
* Include a risk section.
* Include a data quality section.
* Include a source section.
* Include a cost breakdown.
* Include warnings for missing data, failed agents, stale data, low-quality data, or unavailable cost/source metadata.
* Include the required disclaimer.
* Return valid JSON only using the required FinalReport shape.
* Keep every string concise.
* Keep report_markdown compact and avoid repeating the full JSON content in prose.
"""


class ReportWriterAgent(BaseAgent[FinalReport]):
    name = "report_writer_agent"
    output_schema = FinalReport

    def __init__(
        self,
        *,
        llm_provider: BaseLLMProvider | None = None,
        temperature: float = 0.2,
        max_output_tokens: int = 5000,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self.llm_provider = llm_provider
        self.temperature = temperature
        self.max_output_tokens = max_output_tokens

    async def execute(self, context: AnalysisContext) -> AgentExecutionPayload:
        if context.thesis_output is None:
            output = self._fallback_report(context)
            context.final_report = output
            return AgentExecutionPayload(
                status="partial",
                provider="deterministic",
                model="deterministic",
                cost_type="deterministic",
                output=output,
                data_used=self._data_used(context),
                warnings=self._report_warnings(context),
            )

        provider = self.llm_provider or self._create_llm_provider(
            context.request.llm_provider
        )
        try:
            result = await provider.generate_json(
                messages=[
                    {"role": "system", "content": REPORT_WRITER_AGENT_SYSTEM_PROMPT},
                    {"role": "user", "content": self.build_user_prompt(context)},
                ],
                output_schema=FinalReport,
                model=context.request.llm_model,
                agent_name=self.name,
                temperature=self.temperature,
                max_output_tokens=self.max_output_tokens,
            )
        except LLMProviderError as exc:
            if self._should_stop_on_llm_error(exc):
                raise
            output = self._fallback_report(
                context,
                reason=(
                    "The Report Writer Agent used a deterministic fallback because "
                    f"the LLM request failed: {exc}"
                ),
            )
            context.final_report = output
            return AgentExecutionPayload(
                status="partial",
                provider="deterministic",
                model="deterministic",
                cost_type="deterministic",
                output=output,
                data_used=self._data_used(context),
                warnings=output.warnings,
            )

        output = self.validate_output(result.content)
        if not isinstance(output, FinalReport):
            raise TypeError("report writer agent returned an unexpected output type")

        enriched_output = output.model_copy(
            update={
                "symbol": context.request.symbol,
                "market": context.request.market,
                "horizon": context.request.horizon,
                "company_name": self._company_name(context) or output.company_name,
                "created_at": context.updated_at,
                "latest_close": self._latest_close_value(context),
                "disclaimer": DISCLAIMER,
                "cost_breakdown": self._cost_breakdown(
                    context,
                    extra_trace=CostTrace(
                        provider=result.provider,
                        model=result.model,
                        agent_name=self.name,
                        input_tokens=result.input_tokens,
                        output_tokens=result.output_tokens,
                        estimated_cost_usd=result.estimated_cost_usd,
                        cost_type=result.cost_type,
                        duration_ms=result.duration_ms,
                        warnings=result.warnings,
                        parsing_errors=result.parsing_errors,
                    ),
                ),
                "warnings": self._dedupe(
                    [
                        *output.warnings,
                        *self._report_warnings(context),
                    ]
                ),
            }
        )

        context.final_report = enriched_output

        return AgentExecutionPayload(
            status="completed",
            provider=result.provider,
            model=result.model,
            input_tokens=result.input_tokens,
            output_tokens=result.output_tokens,
            estimated_cost_usd=result.estimated_cost_usd,
            cost_type=result.cost_type,
            duration_ms=result.duration_ms,
            output=enriched_output,
            data_used=self._data_used(context),
            warnings=enriched_output.warnings,
            parsing_errors=result.parsing_errors,
        )

    def build_user_prompt(self, context: AnalysisContext) -> str:
        prompt = REPORT_WRITER_AGENT_USER_PROMPT.format(
            symbol=context.request.symbol,
            company_name=self._company_name(context) or "Unknown",
            market=context.request.market,
            created_at=context.updated_at.isoformat(),
            horizon=context.request.horizon,
            analysis_depth=context.request.depth,
            latest_close=self._latest_close(context),
            latest_price_timestamp=self._latest_price_timestamp(context),
            data_collector_output=self._data_collector_output_text(context),
            technical_agent_output=self._technical_output_text(context.technical_output),
            news_sentiment_agent_output=self._news_output_text(
                context.news_sentiment_output
            ),
            bull_case_agent_output=self._bull_case_output_text(context.bull_case_output),
            bear_case_agent_output=self._bear_case_output_text(context.bear_case_output),
            risk_review_agent_output=self._risk_review_output_text(
                context.risk_review_output
            ),
            thesis_agent_output=self._thesis_output_text(context.thesis_output),
            data_quality_score=self._data_quality_score(context),
            price_data_status=self._price_data_status(context),
            news_data_status=self._news_data_status(context),
            company_profile_status=self._company_profile_status(context),
            missing_data=self._join_or_none(self._missing_data(context)),
            provider_names=self._join_or_none(self._provider_names(context)),
            data_quality_warnings=self._join_or_none(self._data_quality_warnings(context)),
            source_metadata=json.dumps(
                [source.model_dump(mode="json") for source in self._source_items(context)],
                indent=2,
                sort_keys=True,
            ),
            cost_tracking_metadata=json.dumps(
                self._cost_breakdown(context).model_dump(mode="json"),
                indent=2,
                sort_keys=True,
            ),
            failed_agent_outputs=self._join_or_none(self._failed_or_missing_outputs(context)),
        )

        structured_payload = {
            "data_collector_output": self._data_collector_output_payload(context),
            "technical_output": self._model_dump_or_none(context.technical_output),
            "news_sentiment_output": self._model_dump_or_none(
                context.news_sentiment_output
            ),
            "bull_case_output": self._model_dump_or_none(context.bull_case_output),
            "bear_case_output": self._model_dump_or_none(context.bear_case_output),
            "risk_review_output": self._model_dump_or_none(context.risk_review_output),
            "thesis_output": self._model_dump_or_none(context.thesis_output),
            "data_quality_section": self._data_quality_section(context).model_dump(
                mode="json"
            ),
            "source_section": [
                item.model_dump(mode="json") for item in self._source_items(context)
            ],
            "cost_breakdown": self._cost_breakdown(context).model_dump(mode="json"),
            "warnings": self._report_warnings(context),
        }
        prompt += (
            "\n\nStructured report payload:\n"
            f"{json.dumps(structured_payload, indent=2, sort_keys=True)}"
        )
        if context.request.custom_question:
            prompt += (
                "\n\nUser research focus: "
                f"{context.request.custom_question.strip()}"
            )
        return prompt

    def _fallback_report(
        self,
        context: AnalysisContext,
        *,
        reason: str | None = None,
    ) -> FinalReport:
        company_name = self._company_name(context) or "Unknown"
        warnings = self._report_warnings(context)
        if reason:
            warnings = self._dedupe([reason, *warnings])
        thesis_output = context.thesis_output
        overall_view = (
            thesis_output.overall_view if thesis_output is not None else "insufficient_data"
        )
        confidence = thesis_output.confidence if thesis_output is not None else 0.1
        investment_thesis = (
            thesis_output.thesis
            if thesis_output is not None
            else (
                "A reliable final investment thesis is unavailable because the "
                "Thesis Agent output is missing from the analysis context."
            )
        )
        base_case = (
            thesis_output.base_case
            if thesis_output is not None
            else "No reliable base case can be formed without a completed thesis."
        )
        bull_case_summary = (
            thesis_output.bull_case_summary
            if thesis_output is not None
            else (
                context.bull_case_output.bull_case
                if context.bull_case_output is not None
                else "Bull case output is unavailable."
            )
        )
        bear_case_summary = (
            thesis_output.bear_case_summary
            if thesis_output is not None
            else (
                context.bear_case_output.bear_case
                if context.bear_case_output is not None
                else "Bear case output is unavailable."
            )
        )
        what_to_watch = (
            list(thesis_output.what_to_watch)
            if thesis_output is not None
            else [
                "Whether the missing thesis output can be regenerated.",
                "Whether missing upstream agents can be rerun successfully.",
                "Whether data quality improves enough for a complete report.",
            ]
        )
        executive_summary = (
            "The report was assembled from deterministic fallbacks because the final "
            "LLM-based report writing step could not be completed."
            if reason
            else (
                "The report could not be completed with a reliable final AI view "
                "because the thesis output is missing. Available upstream research "
                "is preserved below, but the result should be treated as incomplete."
            )
        )
        report = FinalReport(
            title=f"Equity Research Report: {context.request.symbol}",
            symbol=context.request.symbol,
            company_name=company_name,
            market=context.request.market,
            created_at=context.updated_at,
            latest_close=self._latest_close_value(context),
            overall_view=overall_view,
            confidence=confidence,
            horizon=context.request.horizon,
            executive_summary=executive_summary,
            investment_thesis=investment_thesis,
            base_case=base_case,
            bull_case_summary=bull_case_summary,
            bear_case_summary=bear_case_summary,
            what_to_watch=what_to_watch,
            agent_summaries=self._agent_summaries(context),
            risk_section=self._risk_section(context),
            data_quality_section=self._data_quality_section(context),
            source_section=self._source_items(context),
            cost_breakdown=self._cost_breakdown(context),
            warnings=warnings,
            disclaimer=DISCLAIMER,
            report_markdown=self._fallback_markdown(
                symbol=context.request.symbol,
                company_name=company_name,
                overall_view=overall_view,
                confidence=confidence,
                horizon=context.request.horizon,
                executive_summary=executive_summary,
                investment_thesis=investment_thesis,
                base_case=base_case,
                bull_case_summary=bull_case_summary,
                bear_case_summary=bear_case_summary,
                what_to_watch=what_to_watch,
                agent_summaries=self._agent_summaries(context),
                risk_section=self._risk_section(context),
                data_quality_section=self._data_quality_section(context),
                warnings=warnings,
            ),
        )
        return report

    def _agent_summaries(self, context: AnalysisContext) -> AgentSummaries:
        return AgentSummaries(
            technical=(
                context.technical_output.summary
                if context.technical_output is not None
                else "Technical Research Agent output is missing."
            ),
            news_sentiment=(
                context.news_sentiment_output.sentiment_summary
                if context.news_sentiment_output is not None
                else "News & Sentiment Agent output is missing."
            ),
            bull_case=(
                context.bull_case_output.bull_case
                if context.bull_case_output is not None
                else "Bull Case Agent output is missing."
            ),
            bear_case=(
                context.bear_case_output.bear_case
                if context.bear_case_output is not None
                else "Bear Case Agent output is missing."
            ),
            risk_review=(
                self._risk_review_summary(context.risk_review_output)
                if context.risk_review_output is not None
                else "Risk Review Agent output is missing."
            ),
        )

    def _risk_section(self, context: AnalysisContext) -> FinalReportRiskSection:
        if context.risk_review_output is None:
            return FinalReportRiskSection(
                risk_level="insufficient_data",
                risk_score=85,
                main_risks=["Risk Review Agent output is missing."],
                invalidation_conditions=[
                    "A completed risk review is needed to define reliable invalidation conditions."
                ],
                confidence_adjustment=-0.35,
            )
        risk = context.risk_review_output
        return FinalReportRiskSection(
            risk_level=risk.risk_level,
            risk_score=risk.risk_score,
            main_risks=list(risk.main_risks),
            invalidation_conditions=list(risk.invalidation_conditions),
            confidence_adjustment=risk.confidence_adjustment,
        )

    def _data_quality_section(
        self, context: AnalysisContext
    ) -> FinalReportDataQualitySection:
        summary = context.data_quality or DataQualitySummary()
        return FinalReportDataQualitySection(
            data_quality_score=self._raw_data_quality_score(context),
            price_data_status=summary.price_data_status,
            news_data_status=summary.news_data_status,
            company_profile_status=summary.fundamentals_status,
            missing_data=self._missing_data(context),
            providers=self._provider_names(context),
            warnings=self._data_quality_warnings(context),
        )

    def _source_items(self, context: AnalysisContext) -> list[FinalReportSourceItem]:
        items: list[FinalReportSourceItem] = []
        if context.market_data is not None:
            for source in context.market_data.sources:
                items.append(
                    FinalReportSourceItem(
                        name=source.name,
                        type=self._source_type(source.name),
                        provider=source.provider,
                        url=source.url,
                        used_for=self._source_used_for(source.name),
                    )
                )

            for news_item in context.market_data.news:
                items.append(
                    FinalReportSourceItem(
                        name=news_item.source,
                        type="news",
                        provider=news_item.source,
                        url=news_item.url,
                        used_for=f"News context: {news_item.title}",
                    )
                )

        if not items:
            return [
                FinalReportSourceItem(
                    name="Sources unavailable",
                    type="other",
                    provider="unavailable",
                    url=None,
                    used_for="Source metadata was unavailable in the analysis context.",
                )
            ]
        deduped: dict[tuple[str, str, str | None, str], FinalReportSourceItem] = {}
        for item in items:
            key = (item.name, item.provider, item.url, item.used_for)
            deduped.setdefault(key, item)
        return list(deduped.values())

    def _cost_breakdown(
        self,
        context: AnalysisContext,
        *,
        extra_trace: CostTrace | None = None,
    ) -> FinalReportCostBreakdown:
        traces = list(context.cost_traces)
        if extra_trace is not None:
            traces.append(extra_trace)
        items = [
            FinalReportCostItem(
                agent_name=trace.agent_name,
                provider=trace.provider,
                model=trace.model,
                input_tokens=trace.input_tokens,
                output_tokens=trace.output_tokens,
                estimated_cost_usd=trace.estimated_cost_usd,
                cost_type=trace.cost_type,
                duration_ms=trace.duration_ms,
                warnings=list(trace.warnings),
                parsing_errors=list(trace.parsing_errors),
            )
            for trace in traces
        ]
        return FinalReportCostBreakdown(
            total_estimated_cost_usd=round(
                sum(item.estimated_cost_usd for item in items), 8
            ),
            items=items,
        )

    def _report_warnings(self, context: AnalysisContext) -> list[str]:
        warnings = [
            *self._data_quality_warnings(context),
            *self._failed_or_missing_outputs(context),
        ]
        if not context.cost_traces:
            warnings.append("Cost tracking metadata was unavailable.")
        if context.market_data is None or not context.market_data.sources:
            warnings.append("Source metadata was unavailable.")
        if context.thesis_output is None:
            warnings.append("Thesis Agent output is missing.")
        return self._dedupe(warnings)

    def _risk_review_summary(
        self, risk_output: RiskReviewAgentOutput | None
    ) -> str:
        if risk_output is None:
            return "Risk Review Agent output is missing."
        main_risk = risk_output.main_risks[0] if risk_output.main_risks else "none"
        return (
            f"Risk level is {risk_output.risk_level} with a risk score of "
            f"{risk_output.risk_score:.0f}. Main risk: {main_risk}. "
            f"Confidence adjustment: {risk_output.confidence_adjustment:.2f}."
        )

    def _data_collector_output_payload(
        self, context: AnalysisContext
    ) -> dict[str, Any] | None:
        if context.market_data is None and context.data_quality is None:
            return None
        payload = DataCollectorOutput(
            market_data=context.market_data
            if context.market_data is not None
            else MarketDataBundle(
                symbol=context.request.symbol,
                market=context.request.market,
            ),
            data_quality=context.data_quality
            if context.data_quality is not None
            else DataQualitySummary(),
        ).model_dump(mode="json")

        market_payload = payload["market_data"]
        price_history = market_payload.get("price_history")
        if isinstance(price_history, list):
            market_payload["price_history_count"] = len(price_history)
            market_payload["price_history"] = price_history[-PROMPT_PRICE_HISTORY_LIMIT:]

        news_items = market_payload.get("news")
        if isinstance(news_items, list):
            market_payload["news_count"] = len(news_items)
            market_payload["news"] = news_items[:PROMPT_NEWS_LIMIT]

        sources = market_payload.get("sources")
        if isinstance(sources, list):
            market_payload["sources_count"] = len(sources)
            market_payload["sources"] = sources[:PROMPT_SOURCES_LIMIT]

        company_profile = market_payload.get("company_profile")
        if isinstance(company_profile, dict):
            company_profile.pop("description", None)

        return payload

    def _data_collector_output_text(self, context: AnalysisContext) -> str:
        payload = self._data_collector_output_payload(context)
        if payload is None:
            return "Data Collector output is missing."
        return json.dumps(payload, indent=2, sort_keys=True)

    def _technical_output_text(
        self, technical_output: TechnicalAgentOutput | None
    ) -> str:
        if technical_output is None:
            return "Technical Research Agent output is missing."
        return json.dumps(technical_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _news_output_text(self, news_output: NewsSentimentOutput | None) -> str:
        if news_output is None:
            return "News & Sentiment Agent output is missing."
        return json.dumps(news_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _bull_case_output_text(self, bull_output: BullCaseAgentOutput | None) -> str:
        if bull_output is None:
            return "Bull Case Agent output is missing."
        return json.dumps(bull_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _bear_case_output_text(self, bear_output: BearCaseAgentOutput | None) -> str:
        if bear_output is None:
            return "Bear Case Agent output is missing."
        return json.dumps(bear_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _risk_review_output_text(
        self, risk_output: RiskReviewAgentOutput | None
    ) -> str:
        if risk_output is None:
            return "Risk Review Agent output is missing."
        return json.dumps(risk_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _thesis_output_text(self, thesis_output: ThesisAgentOutput | None) -> str:
        if thesis_output is None:
            return "Thesis Agent output is missing."
        return json.dumps(thesis_output.model_dump(mode="json"), indent=2, sort_keys=True)

    def _company_name(self, context: AnalysisContext) -> str | None:
        if context.market_data and context.market_data.company_profile:
            return context.market_data.company_profile.name
        return None

    def _latest_close(self, context: AnalysisContext) -> str:
        if context.market_data and context.market_data.price_history:
            return self._format_float(context.market_data.price_history[-1].close)
        if context.market_data and context.market_data.quote:
            return self._format_float(context.market_data.quote.price)
        return "unavailable"

    def _latest_close_value(self, context: AnalysisContext) -> float | None:
        if context.market_data and context.market_data.price_history:
            return context.market_data.price_history[-1].close
        if context.market_data and context.market_data.quote:
            return context.market_data.quote.price
        return None

    def _latest_price_timestamp(self, context: AnalysisContext) -> str:
        if context.market_data and context.market_data.price_history:
            return self._format_datetime(context.market_data.price_history[-1].timestamp)
        if context.market_data and context.market_data.quote:
            return self._format_datetime(context.market_data.quote.as_of)
        return "unavailable"

    def _data_quality_score(self, context: AnalysisContext) -> str:
        score = self._raw_data_quality_score(context)
        if score is None:
            return "unavailable"
        return f"{score:.2f}"

    def _raw_data_quality_score(self, context: AnalysisContext) -> float | None:
        if context.data_quality and context.data_quality.score is not None:
            return context.data_quality.score
        if context.market_data and context.market_data.data_quality_score is not None:
            return context.market_data.data_quality_score
        return None

    def _price_data_status(self, context: AnalysisContext) -> str:
        if context.data_quality is not None:
            return context.data_quality.price_data_status
        return "missing"

    def _news_data_status(self, context: AnalysisContext) -> str:
        if context.data_quality is not None:
            return context.data_quality.news_data_status
        return "missing"

    def _company_profile_status(self, context: AnalysisContext) -> str:
        if context.data_quality is not None:
            return context.data_quality.fundamentals_status
        return "missing"

    def _missing_data(self, context: AnalysisContext) -> list[str]:
        if context.data_quality is not None:
            return list(context.data_quality.missing_data)
        if context.market_data is not None:
            return list(context.market_data.missing_data)
        return []

    def _provider_names(self, context: AnalysisContext) -> list[str]:
        if context.data_quality and context.data_quality.provider_names:
            return list(context.data_quality.provider_names)
        if context.market_data and context.market_data.sources:
            return [source.provider for source in context.market_data.sources]
        return []

    def _data_quality_warnings(self, context: AnalysisContext) -> list[str]:
        warnings: list[str] = []
        if context.data_quality is not None:
            warnings.extend(context.data_quality.warnings)
        if context.market_data is not None:
            warnings.extend(context.market_data.warnings)
        warnings.extend(context.warnings)
        return self._dedupe(warnings)

    def _failed_or_missing_outputs(self, context: AnalysisContext) -> list[str]:
        missing: list[str] = []
        if context.market_data is None and context.data_quality is None:
            missing.append("Data Collector output is missing.")
        if context.technical_output is None:
            missing.append("Technical Research Agent output is missing.")
        if context.news_sentiment_output is None:
            missing.append("News & Sentiment Agent output is missing.")
        if context.bull_case_output is None:
            missing.append("Bull Case Agent output is missing.")
        if context.bear_case_output is None:
            missing.append("Bear Case Agent output is missing.")
        if context.risk_review_output is None:
            missing.append("Risk Review Agent output is missing.")
        if context.thesis_output is None:
            missing.append("Thesis Agent output is missing.")
        for agent_result in context.agent_results:
            if agent_result.status == "failed":
                missing.append(
                    f"{agent_result.agent_name} failed: "
                    f"{agent_result.error_message or 'unknown error'}"
                )
        return self._dedupe(missing)

    def _data_used(self, context: AnalysisContext) -> list[str]:
        data_used: list[str] = []
        if context.market_data is not None:
            data_used.append("market_data")
        if context.data_quality is not None:
            data_used.append("data_quality")
        if context.technical_output is not None:
            data_used.append("technical_output")
        if context.news_sentiment_output is not None:
            data_used.append("news_sentiment_output")
        if context.bull_case_output is not None:
            data_used.append("bull_case_output")
        if context.bear_case_output is not None:
            data_used.append("bear_case_output")
        if context.risk_review_output is not None:
            data_used.append("risk_review_output")
        if context.thesis_output is not None:
            data_used.append("thesis_output")
        if context.cost_traces:
            data_used.append("cost_traces")
        return data_used

    def _fallback_markdown(
        self,
        *,
        symbol: str,
        company_name: str,
        overall_view: str,
        confidence: float,
        horizon: str,
        executive_summary: str,
        investment_thesis: str,
        base_case: str,
        bull_case_summary: str,
        bear_case_summary: str,
        what_to_watch: Sequence[str],
        agent_summaries: AgentSummaries,
        risk_section: FinalReportRiskSection,
        data_quality_section: FinalReportDataQualitySection,
        warnings: Sequence[str],
    ) -> str:
        lines = [
            f"# Equity Research Report: {symbol}",
            "",
            f"Company: {company_name}",
            f"AI View: {overall_view}",
            f"Confidence: {confidence:.2f}",
            f"Horizon: {horizon}",
            "",
            "## Executive Summary",
            executive_summary,
            "",
            "## Investment Thesis",
            investment_thesis,
            "",
            "## Base Case",
            base_case,
            "",
            "## Bull Case",
            bull_case_summary,
            "",
            "## Bear Case",
            bear_case_summary,
            "",
            "## What to Watch",
        ]
        lines.extend(f"- {item}" for item in what_to_watch)
        lines.extend(
            [
                "",
                "## Agent Summaries",
                f"- Technical: {agent_summaries.technical}",
                f"- News & Sentiment: {agent_summaries.news_sentiment}",
                f"- Bull Case: {agent_summaries.bull_case}",
                f"- Bear Case: {agent_summaries.bear_case}",
                f"- Risk Review: {agent_summaries.risk_review}",
                "",
                "## Risk Section",
                f"- Risk level: {risk_section.risk_level}",
                f"- Risk score: {risk_section.risk_score:.0f}",
                f"- Confidence adjustment: {risk_section.confidence_adjustment:.2f}",
            ]
        )
        lines.extend(f"- Main risk: {item}" for item in risk_section.main_risks)
        lines.extend(
            f"- Invalidation condition: {item}"
            for item in risk_section.invalidation_conditions
        )
        lines.extend(
            [
                "",
                "## Data Quality",
                f"- Data quality score: {data_quality_section.data_quality_score if data_quality_section.data_quality_score is not None else 'unavailable'}",
                f"- Price data status: {data_quality_section.price_data_status}",
                f"- News data status: {data_quality_section.news_data_status}",
                f"- Company profile status: {data_quality_section.company_profile_status}",
            ]
        )
        lines.extend(f"- Missing data: {item}" for item in data_quality_section.missing_data)
        lines.extend(f"- Provider: {item}" for item in data_quality_section.providers)
        lines.extend(f"- Data warning: {item}" for item in data_quality_section.warnings)
        if warnings:
            lines.extend(["", "## Warnings"])
            lines.extend(f"- {warning}" for warning in warnings)
        lines.extend(["", "## Disclaimer", DISCLAIMER])
        return "\n".join(lines)

    def _source_type(self, source_name: str) -> str:
        name = source_name.strip().lower()
        if "news" in name or "rss" in name:
            return "news"
        if "price" in name or "quote" in name:
            return "price"
        if "profile" in name or "company" in name:
            return "profile"
        if "financial" in name or "sec" in name or "fact" in name:
            return "financials"
        return "other"

    def _source_used_for(self, source_name: str) -> str:
        source_type = self._source_type(source_name)
        mapping = {
            "price": "Price history and latest price context.",
            "news": "News and sentiment context.",
            "profile": "Company profile context.",
            "financials": "Fundamental and financial context.",
            "other": "General supporting context.",
        }
        return mapping[source_type]

    def _model_dump_or_none(self, value: Any) -> dict[str, Any] | None:
        if value is None:
            return None
        return value.model_dump(mode="json")

    def _join_or_none(self, values: Sequence[str]) -> str:
        if not values:
            return "none"
        return "; ".join(values)

    def _format_float(self, value: float) -> str:
        return f"{value:.2f}"

    def _format_datetime(self, value: datetime) -> str:
        return value.isoformat()

    def _dedupe(self, values: Sequence[str]) -> list[str]:
        deduped: dict[str, None] = {}
        for value in values:
            stripped = value.strip()
            if stripped:
                deduped.setdefault(stripped, None)
        return list(deduped)


__all__ = [
    "REPORT_WRITER_AGENT_SYSTEM_PROMPT",
    "REPORT_WRITER_AGENT_USER_PROMPT",
    "ReportWriterAgent",
]
